ALTER TABLE `clan_introductions`  ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `comments`  ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `forums`  ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `registered_gameservers` ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `posts`  ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `topics`  ENGINE=InnoDB DEFAULT CHARSET=utf8;