ALTER TABLE `custom_armorsets`
ADD `skill_lvl` TINYINT UNSIGNED NOT NULL default 0 AFTER `skill_id`,
MODIFY id SMALLINT UNSIGNED NOT NULL auto_increment,
MODIFY chest SMALLINT UNSIGNED NOT NULL default 0,
MODIFY legs SMALLINT UNSIGNED NOT NULL default 0,
MODIFY head SMALLINT UNSIGNED NOT NULL default 0,
MODIFY gloves SMALLINT UNSIGNED NOT NULL default 0,
MODIFY feet SMALLINT UNSIGNED NOT NULL default 0,
MODIFY skill_id SMALLINT UNSIGNED NOT NULL default 0,
MODIFY skill_lvl TINYINT UNSIGNED NOT NULL default 0,
MODIFY shield SMALLINT UNSIGNED NOT NULL default 0,
MODIFY shield_skill_id SMALLINT UNSIGNED NOT NULL default 0,
MODIFY enchant6skill SMALLINT UNSIGNED NOT NULL default 0;