ALTER TABLE `pets` DROP `armor`;
ALTER TABLE `pets` DROP `weapon`;
ALTER TABLE `pets` DROP `jewel`;
DROP TABLE IF EXISTS armor;
DROP TABLE IF EXISTS etcitem;
DROP TABLE IF EXISTS weapon;
DROP TABLE IF EXISTS custom_armor;
DROP TABLE IF EXISTS custom_etcitem;
DROP TABLE IF EXISTS custom_weapon;