ALTER TABLE `auction_bid` MODIFY `maxBid` BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `auction` MODIFY `itemQuantity` BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `auction` MODIFY `startingBid` BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `auction` MODIFY `currentBid` BIGINT UNSIGNED NOT NULL DEFAULT 0;